[project]
name = "python-learn"
version = "0.1.0"
description = "learning python"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.uv.workspace]
members = [
    "pytorch-learn",
    "data-analysis",
    "multiprocessing",
    "sklearn",
    "web-scraping",
    "threading",
]
