[project]
name = "pytorch-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Huayu Zhang", email = "zhanghuayu.dev@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "opencv-python>=5.0.0.93",
    "tensorboard>=2.21.0",
    "torch-tb-profiler>=0.4.3",
]

[project.scripts]
pytorch-learn = "pytorch_learn:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
